services:
  backend:
    build: ./backend
    environment:
      PORT: "3000"
      LIVEKIT_API_KEY: "devkey"
      LIVEKIT_API_SECRET: "secret"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  livekit:
    image: livekit/livekit-server:latest
    command: --dev --bind 0.0.0.0 --node-ip 127.0.0.1
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
